# Generated by Django 5.1.6 on 2025-04-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcar",
            name="credit_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="credit_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_cars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
