# Generated by Django 5.1.6 on 2025-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_newcar_credit_available_usedcar_credit_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newcar",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Седан"),
                    ("hatchback", "Хэтчбек"),
                    ("suv", "Внедорожник (SUV)"),
                    ("coupe", "Купе"),
                    ("convertible", "Кабриолет"),
                    ("wagon", "Универсал"),
                    ("pickup", "Пикап"),
                    ("van", "Фургон"),
                    ("minivan", "Минивэн"),
                    ("liftback", "Лифтбэк"),
                    ("fastback", "Фастбэк"),
                    ("roadster", "Родстер"),
                    ("targa", "Тарга"),
                    ("crossover", "Кроссовер"),
                    ("microcar", "Микроавтомобиль"),
                    ("limousine", "Лимузин"),
                    ("panel_van", "Грузовой фургон"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Седан"),
                    ("hatchback", "Хэтчбек"),
                    ("suv", "Внедорожник (SUV)"),
                    ("coupe", "Купе"),
                    ("convertible", "Кабриолет"),
                    ("wagon", "Универсал"),
                    ("pickup", "Пикап"),
                    ("van", "Фургон"),
                    ("minivan", "Минивэн"),
                    ("liftback", "Лифтбэк"),
                    ("fastback", "Фастбэк"),
                    ("roadster", "Родстер"),
                    ("targa", "Тарга"),
                    ("crossover", "Кроссовер"),
                    ("microcar", "Микроавтомобиль"),
                    ("limousine", "Лимузин"),
                    ("panel_van", "Грузовой фургон"),
                ],
                max_length=50,
            ),
        ),
    ]
