# Generated by Django 5.1.6 on 2025-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_newcar_body_type_alter_usedcar_body_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newcar",
            name="engine",
            field=models.CharField(
                choices=[
                    ("gasoline", "Бензиновый"),
                    ("diesel", "Дизельный"),
                    ("hybrid", "Гибрид"),
                    ("EV", "Электрический"),
                    ("lpg", "Газ (LPG)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="engine",
            field=models.CharField(
                choices=[
                    ("gasoline", "Бензиновый"),
                    ("diesel", "Дизельный"),
                    ("hybrid", "Гибрид"),
                    ("EV", "Электрический"),
                    ("lpg", "Газ (LPG)"),
                ],
                max_length=20,
            ),
        ),
    ]
