# Generated by Django 5.1.6 on 2025-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newcar",
            options={"verbose_name": "Новое авто", "verbose_name_plural": "Новые авто"},
        ),
        migrations.AddField(
            model_name="newcar",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newcar",
            name="warranty_years",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="newcar",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="media/cars/"),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="media/cars/"),
        ),
    ]
