# Generated by Django 5.1.6 on 2025-04-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_newcar_options_newcar_in_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="brand_logos/")),
                ("description", models.TextField(blank=True)),
                (
                    "auto_centers",
                    models.ManyToManyField(related_name="brands", to="main.autocenter"),
                ),
            ],
        ),
    ]
