# Generated by Django 5.1.6 on 2025-05-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_carbrand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newcar",
            name="images",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="images",
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.usedcar",
                    ),
                ),
            ],
        ),
    ]
