# Generated by Django 5.1.6 on 2025-05-08 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_newcar_images_remove_usedcar_images_carimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcar",
            name="auto_center",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.autocenter",
            ),
        ),
        migrations.AddField(
            model_name="newcar",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newcar",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="main.autocenter",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Покупатель"),
                    ("dealer_employee", "Сотрудник автосалона"),
                    ("admin", "Администратор"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NewCarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="new_cars/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.newcar",
                    ),
                ),
            ],
        ),
    ]
